import { ingredients, orders, counts, insidePizza, scorePizza, pizzaCoverage, orderIndexForServed, levelFromServed } from './engine.js';
import { createBase, drawIngredient, makeIcon } from './art.js';
const $=id=>document.getElementById(id), canvas=$('pizzaCanvas'), ctx=canvas.getContext('2d'), base=createBase();
const PIECE_SIZE_MIN=1.45, PIECE_SIZE_RANGE=.2, PREVIEW_SIZE=1.55, ERASE_RADIUS=65, KEYBOARD_RING=58;
let pieces=[], history=[], selected='salami', erasing=false, mode='orders', baking=false, completed=false, pointer=null, keyboard=false, sound=false, audioContext, toastTimer, dragId=null;
let save={coins:0,served:0};try{const data=JSON.parse(localStorage.getItem('pizza-piccola'));if(data&&Number.isSafeInteger(data.coins)&&data.coins>=0&&Number.isSafeInteger(data.served)&&data.served>=0)save=data;}catch{}
let orderIndex=orderIndexForServed(save.served);
function persist(){try{localStorage.setItem('pizza-piccola',JSON.stringify(save));}catch{}}
function notify(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600);}
function play(freq=440,duration=.08){if(!sound)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.65,audioContext.currentTime+duration);g.gain.setValueAtTime(.06,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+duration);}catch{}}
function pieceWord(n){return n===1?'składnik':n%10>=2&&n%10<=4&&(n%100<12||n%100>14)?'składniki':'składników';}
function chefAdvice(actual){
  if(mode==='free')return 'Nie ma złych pomysłów. Mieszaj kolory i smaki, a potem zobacz swoją pizzę prosto z pieca.';
  if(!pieces.length)return 'Rozłóż składniki na całym placku — od środka aż po brzeg. Niech każdy kawałek smakuje tak samo dobrze.';
  const order=orders[orderIndex];
  for(const [id,target] of Object.entries(order.recipe)){if((actual[id]||0)>target)return `Za dużo: ${ingredients.find(i=>i.id===id).name}. Zabierz nadmiar gumką albo cofnij ruch.`;}
  for(const id of Object.keys(actual)){if(!order.recipe[id])return `Ten składnik nie jest w zamówieniu. Zostaw tylko to, o co prosi ${order.name}.`;}
  const cov=pizzaCoverage(pieces);
  if(cov.emptyCenter)return 'Środek pizzy jeszcze pusty. Połóż kilka dodatków bliżej środka.';
  if(cov.emptyEdge)return 'Brzeg jeszcze pusty. Sięgnij bliżej skórki — klient chce pełny placek.';
  if(cov.emptySectors>=2)return 'Kilka kawałków jest pustych. Rozłóż dodatki równomiernie wokół całego koła.';
  if(cov.emptySectors===1)return 'Jeden wycinek jeszcze czeka. Dopełnij go, żeby pizza była równa.';
  if(cov.coverage<0.55)return 'Placek wciąż wygląda na rzadki. Rozłóż porcje szerzej, nie tylko w jednym miejscu.';
  const missing=Object.entries(order.recipe).filter(([id,n])=>(actual[id]||0)<n);
  if(missing.length)return 'Dobrze idzie pokrycie! Dokończ brakujące ilości z biletu zamówienia.';
  return 'Pięknie obłożone! Sprawdź liczby na bilecie i wkładaj do pieca.';
}
function render(){ctx.clearRect(0,0,900,900);ctx.drawImage(base,0,0);for(const p of pieces)drawIngredient(ctx,p.id,p.x,p.y,p.size,p.rotation,p.seed);if(pointer&&insidePizza(pointer.x,pointer.y)&&!baking&&!completed){if(erasing){ctx.strokeStyle='#b54432';ctx.lineWidth=2;ctx.beginPath();ctx.arc(pointer.x,pointer.y,ERASE_RADIUS*.85,0,Math.PI*2);ctx.stroke();}else{ctx.globalAlpha=.48;drawIngredient(ctx,selected,pointer.x,pointer.y,PREVIEW_SIZE,0,8);ctx.globalAlpha=1;}if(keyboard){ctx.strokeStyle='#344c38';ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(pointer.x,pointer.y,KEYBOARD_RING,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}}}
function update(){const actual=counts(pieces);const cov=pizzaCoverage(pieces);const covPct=Math.round(cov.coverage*100);
  $('pieceCount').textContent=`${pieces.length} ${pieceWord(pieces.length)} na placku`;
  $('coverageHint').textContent=pieces.length?`pokrycie ${covPct}%`:'pokrycie —';
  $('coverageHint').dataset.level=covPct>=70?'good':covPct>=40?'ok':'low';
  for(const li of $('recipe').children){const id=li.dataset.id;if(!id)continue;const target=orders[orderIndex].recipe[id],n=actual[id]||0;li.querySelector('.recipe-amount').textContent=`${n} / ${target}${n===target?' ✓':''}`;li.classList.toggle('complete',n===target);li.classList.toggle('over',n>target);}
  if(!baking&&!completed)$('chefTip').textContent=chefAdvice(actual);
  $('undoBtn').disabled=!history.length||baking||completed;$('clearBtn').disabled=!pieces.length||baking||completed;$('eraseBtn').disabled=baking||completed;$('bakeBtn').disabled=baking;
  $('bakeBtn').innerHTML=completed?'Zobacz wypiek <span>↗</span>':'Do pieca! <span>♨</span>';
  $('coins').textContent=save.coins;$('level').textContent=levelFromServed(save.served);$('rank').textContent=save.served>=9?'Maestro della pizza':save.served>=3?'Pizzaiolo z pasją':'Początkujący pizzaiolo';render();}
function select(id){if(baking||completed)return;selected=id;erasing=false;$('eraseBtn').classList.remove('active');$('eraseBtn').setAttribute('aria-pressed','false');for(const btn of $('ingredients').children){const active=btn.dataset.id===id;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',String(active));}$('selectedIcon').replaceChildren(makeIcon(id,50,50,true));$('canvasHint').textContent=`${ingredients.find(i=>i.id===id).name} — kliknij na pizzy, aby dodać`;render();}
function loadOrder(){const order=orders[orderIndex],free=mode==='free';$('orderNumber').textContent=free?'TWOJA AUTORSKA PIZZA':`ZAMÓWIENIE #${String(save.served+1).padStart(3,'0')}`;$('customerName').textContent=free?'Dziś Ty jesteś szefem!':`Ciao, jestem ${order.name}!`;$('customerSubtitle').textContent=free?'Bez przepisu. Bez ograniczeń.':order.subtitle;document.querySelector('.avatar').textContent=free?'🧑‍🍳':order.avatar;$('orderQuote').textContent=free?'„Odrobina tego, więcej tamtego… Stwórz pizzę dokładnie taką, jak lubisz.”':`„${order.quote}”`;$('ticketTitle').textContent=free?'La tua creazione':order.title;$('reward').textContent=free?'Radość tworzenia ♥':`do ${order.reward} monet ✦`;$('workspaceLabel').textContent=free?'TWÓJ BLAT · PEŁNA SWOBODA':'TWÓJ BLAT';$('recipe').replaceChildren();
  if(free){const li=document.createElement('li');li.textContent='Wszystkie składniki do Twojej dyspozycji.';$('recipe').append(li);}else for(const [id,n]of Object.entries(order.recipe)){const li=document.createElement('li');li.dataset.id=id;li.append(makeIcon(id,50,50,true));const name=document.createElement('span');name.textContent=ingredients.find(i=>i.id===id).name;const amount=document.createElement('span');amount.className='recipe-amount';amount.textContent=`0 / ${n}`;li.append(name,amount);$('recipe').append(li);}
  for(const btn of $('ingredients').children)btn.querySelector('.needed').textContent=!free&&order.recipe[btn.dataset.id]?'✦':'';
  update();}
for(const ingredient of ingredients){const btn=document.createElement('button');btn.className='ingredient';btn.dataset.id=ingredient.id;btn.draggable=true;btn.setAttribute('aria-label',ingredient.name);btn.setAttribute('aria-pressed','false');const dot=document.createElement('span');dot.className='selected-dot';const needed=document.createElement('span');needed.className='needed';needed.title='Składnik z zamówienia';const label=document.createElement('b');label.textContent=ingredient.name;btn.append(dot,needed,makeIcon(ingredient.id),label);btn.addEventListener('click',()=>select(ingredient.id));btn.addEventListener('dragstart',e=>{if(baking||completed){e.preventDefault();return;}select(ingredient.id);dragId=ingredient.id;e.dataTransfer.setData('text/plain',ingredient.id);e.dataTransfer.effectAllowed='copy';});btn.addEventListener('dragend',()=>{dragId=null;pointer=null;render();});$('ingredients').append(btn);}
function position(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*900/r.width,y:(e.clientY-r.top)*900/r.height};}
function addAt(pos){if(baking||completed)return;if(!insidePizza(pos.x,pos.y)){notify('Połóż składnik na środku pizzy, zostawiając wolny brzeg.');return;}if(erasing){let index=-1;for(let i=pieces.length-1;i>=0;i--)if(Math.hypot(pieces[i].x-pos.x,pieces[i].y-pos.y)<ERASE_RADIUS){index=i;break;}if(index>=0){history.push(pieces.slice());pieces.splice(index,1);play(220);}else notify('Kliknij składnik, który chcesz usunąć.');}else{if(pieces.length>=100){notify('To już 100 dodatków! Czas włożyć pizzę do pieca.');return;}history.push(pieces.slice());pieces.push({id:selected,...pos,rotation:Math.random()*Math.PI*2,size:PIECE_SIZE_MIN+Math.random()*PIECE_SIZE_RANGE,seed:Math.floor(Math.random()*10000)});play(400+Math.random()*180);}update();}
let touchPlacing=false;
canvas.addEventListener('pointermove',e=>{keyboard=false;pointer=position(e);render();});
canvas.addEventListener('pointerleave',e=>{if(e.pointerType==='touch'&&touchPlacing)return;pointer=null;render();});
canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;keyboard=false;const pos=position(e);if(e.pointerType==='touch'){touchPlacing=true;pointer=pos;try{canvas.setPointerCapture(e.pointerId);}catch{}render();return;}pointer=null;addAt(pos);});
canvas.addEventListener('pointerup',e=>{if(e.pointerType!=='touch'||!touchPlacing)return;touchPlacing=false;addAt(position(e));pointer=null;render();});
canvas.addEventListener('pointercancel',()=>{touchPlacing=false;pointer=null;render();});
canvas.addEventListener('dragover',e=>{if(dragId&&!baking&&!completed){e.preventDefault();e.dataTransfer.dropEffect='copy';pointer=position(e);render();}});canvas.addEventListener('drop',e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(ingredients.some(i=>i.id===id)){select(id);pointer=null;addAt(position(e));}dragId=null;});
canvas.addEventListener('focus',()=>{if(!pointer){keyboard=true;pointer={x:450,y:450};render();}});canvas.addEventListener('blur',()=>{pointer=null;render();});canvas.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter',' '].includes(e.key)){e.preventDefault();keyboard=true;pointer??={x:450,y:450};if(e.key==='Enter'||e.key===' ')addAt(pointer);else{const next={...pointer};next.x+=(e.key==='ArrowRight'?25:e.key==='ArrowLeft'?-25:0);next.y+=(e.key==='ArrowDown'?25:e.key==='ArrowUp'?-25:0);if(insidePizza(next.x,next.y))pointer=next;}render();}});
function undo(){if(baking||completed||!history.length)return;pieces=history.pop();update();play(250);}$('undoBtn').onclick=undo;document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!$('helpDialog').open&&!$('resultDialog').open){e.preventDefault();undo();}});
$('eraseBtn').onclick=()=>{if(baking||completed)return;erasing=!erasing;$('eraseBtn').classList.toggle('active',erasing);$('eraseBtn').setAttribute('aria-pressed',String(erasing));$('canvasHint').textContent=erasing?'Kliknij dodatek na pizzy, aby go usunąć':`${ingredients.find(i=>i.id===selected).name} — kliknij na pizzy, aby dodać`;render();};
$('clearBtn').onclick=()=>{if(baking||completed)return;history.push(pieces.slice());pieces=[];update();notify('Czysty placek, nowe możliwości. Możesz cofnąć ten ruch.');};
const drafts={orders:null,free:null};function setMode(next){if(baking||next===mode)return;if(completed){reset();}drafts[mode]={pieces:pieces.slice(),history:history.slice(),selected};mode=next;const draft=drafts[mode];pieces=draft?.pieces||[];history=draft?.history||[];completed=false;select(draft?.selected||(mode==='orders'?Object.keys(orders[orderIndex].recipe)[0]:'basil'));for(const id of ['ordersMode','freeMode']){const active=id===(mode==='orders'?'ordersMode':'freeMode');$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',String(active));}loadOrder();}
$('ordersMode').onclick=()=>setMode('orders');$('freeMode').onclick=()=>setMode('free');
function reset(){if(completed&&mode==='orders')orderIndex=orderIndexForServed(save.served);pieces=[];history=[];pointer=null;completed=false;select(mode==='orders'?Object.keys(orders[orderIndex].recipe)[0]:'basil');loadOrder();}
function resultFeedback(result){
  if(result.accuracy<100)return 'Sprawdź proporcje: brakujące i nadmiarowe dodatki obniżają ocenę. Następna pizza będzie jeszcze lepsza!';
  if(result.coverage<75)return 'Ilości się zgadzają, ale placek wciąż ma puste miejsca. Rozłóż dodatki od środka po brzeg.';
  if(result.spread<80)return 'Składniki i pokrycie są dobre! Rozłóż je jeszcze równiej wokół koła.';
  return 'Idealne proporcje i pełny placek. Klient już planuje kolejną wizytę!';
}
$('bakeBtn').onclick=()=>{if(baking)return;if(completed){$('resultDialog').showModal();return;}baking=true;pointer=null;render();$('bakingOverlay').hidden=false;document.querySelector('.workstation').classList.add('baking');$('ordersMode').disabled=true;$('freeMode').disabled=true;for(const btn of $('ingredients').children)btn.disabled=true;update();play(180,.4);
  setTimeout(()=>{baking=false;completed=true;$('bakingOverlay').hidden=true;document.querySelector('.workstation').classList.remove('baking');$('ordersMode').disabled=false;$('freeMode').disabled=false;for(const btn of $('ingredients').children)btn.disabled=false;render();$('resultImage').src=canvas.toDataURL('image/png');
    if(mode==='orders'){const result=scorePizza(pieces,orders[orderIndex].recipe,orders[orderIndex].reward);save.coins+=result.earned;save.served++;persist();$('stars').textContent='★'.repeat(result.stars)+'☆'.repeat(3-result.stars);$('resultTitle').textContent=result.score>=90?'Mamma mia!':result.score>=65?'Molto bene!':result.score>=30?'Jeszcze odrobina wprawy.':'Każdy szef kiedyś zaczynał.';$('resultDescription').textContent=resultFeedback(result);$('resultStats').innerHTML=`<span><b>${result.accuracy}%</b>Zgodność</span><span><b>${result.coverage}%</b>Pokrycie</span><span><b>+${result.earned}</b>Monety</span>`;$('nextBtn').innerHTML='Kolejne zamówienie <span>→</span>';
    }else{$('stars').textContent='♥';$('resultTitle').textContent='La tua pizza!';$('resultDescription').textContent='Jedyna w swoim rodzaju. Zrobiona po Twojemu i gotowa do podania. Buon appetito!';$('resultStats').innerHTML=`<span><b>${pieces.length}</b>Dodatków</span><span><b>${Object.keys(counts(pieces)).length}</b>Rodzajów składników</span><span><b>${Math.round(pizzaCoverage(pieces).coverage*100)}%</b>Pokrycie</span>`;$('nextBtn').innerHTML='Zrób kolejną pizzę <span>→</span>';}
    update();$('resultDialog').showModal();play(660,.22);setTimeout(()=>play(880,.3),180);
  },2800);
};
$('nextBtn').onclick=()=>{$('resultDialog').close();reset();};$('closeResult').onclick=()=>$('resultDialog').close();$('helpBtn').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();$('startBtn').onclick=()=>$('helpDialog').close();
$('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').setAttribute('aria-pressed',String(sound));$('soundBtn').querySelector('span').textContent=sound?'Dźwięk włączony':'Dźwięk wyłączony';play(520);};
select('salami');loadOrder();
